version: "3.1"
services:
  www:
    build: .
    ports:
      - "9000:80"
    volumes:
      - .:/var/www/html:delegated
    networks:
      - default
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9003 remote_enable=1
